"""Add suborder total to suborders

Revision ID: 09a40dc15d98
Revises: f53948304744
Create Date: 2023-04-20 12:35:53.711812

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '09a40dc15d98'
down_revision = 'f53948304744'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suborders', sa.Column('total', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suborders', 'total')
    # ### end Alembic commands ###
