"""Add suborder total to suborders

Revision ID: 09a40dc15d98
Revises: f53948304744
Create Date: 2023-04-20 12:35:53.711812

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '09a40dc15d98'
down_revision = 'f53948304744'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property_card_old')
    op.add_column('suborders', sa.Column('total', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suborders', 'total')
    op.create_table('property_card_old',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('borough', postgresql.ENUM('Bronx', 'Manhattan', 'Staten Island', 'Brooklyn', 'Queens', name='borough'), autoincrement=False, nullable=True),
    sa.Column('block', sa.VARCHAR(length=9), autoincrement=False, nullable=True),
    sa.Column('lot', sa.VARCHAR(length=9), autoincrement=False, nullable=True),
    sa.Column('building_number', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('street', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('certified', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('mail', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('contact_info', sa.VARCHAR(length=35), autoincrement=False, nullable=True),
    sa.Column('suborder_number', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['suborder_number'], ['suborders.id'], name='property_card_suborder_number_fkey'),
    sa.PrimaryKeyConstraint('id', name='property_card_pkey')
    )
    # ### end Alembic commands ###
