"""empty message

Revision ID: 233e7da60ca7
Revises: 4ba6d29ce27f
Create Date: 2017-02-27 10:56:15.352521

"""

# revision identifiers, used by Alembic.
revision = '233e7da60ca7'
down_revision = '4ba6d29ce27f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'client_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'client_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    ### end Alembic commands ###
