"""Update nullable columns

Revision ID: 32c352490472
Revises: 3bb2c6ca0e3e
Create Date: 2018-10-02 00:34:43.822096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32c352490472'
down_revision = '3bb2c6ca0e3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'client_data',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('orders', 'confirmation_message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('suborders', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('suborders', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('orders', 'confirmation_message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('orders', 'client_data',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
