"""Create OrderNumberCounter table

Revision ID: 3bb2c6ca0e3e
Revises: 0ce1cf864a34
Create Date: 2018-07-26 14:25:19.158902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bb2c6ca0e3e'
down_revision = '0ce1cf864a34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_number_counter',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('next_order_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('year')
    )
    op.add_column('orders', sa.Column('next_suborder_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'next_suborder_number')
    op.drop_table('order_number_counter')
    # ### end Alembic commands ###
