"""Add father_name and mother_name to death tables

Revision ID: 423df681c81f
Revises: 45f1d8d1f62a
Create Date: 2020-08-26 11:59:52.618393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '423df681c81f'
down_revision = '45f1d8d1f62a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('death_cert', sa.Column('father_name', sa.String(length=30), nullable=True))
    op.add_column('death_cert', sa.Column('mother_name', sa.String(length=30), nullable=True))
    op.add_column('death_search', sa.Column('father_name', sa.String(length=30), nullable=True))
    op.add_column('death_search', sa.Column('mother_name', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('death_cert', 'father_name')
    op.drop_column('death_cert', 'mother_name')
    op.drop_column('death_search', 'father_name')
    op.drop_column('death_search', 'mother_name')
    # ### end Alembic commands ###
