"""Add image_id to TaxPhoto

Revision ID: 45f1d8d1f62a
Revises: 2d6ce5f0bea2
Create Date: 2019-09-10 16:57:47.091906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45f1d8d1f62a'
down_revision = '2d6ce5f0bea2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tax_photo', sa.Column('image_id', sa.String(length=35), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tax_photo', 'image_id')
    # ### end Alembic commands ###
