"""Initial Migration

Revision ID: 4ba6d29ce27f
Revises: None
Create Date: 2017-02-24 12:22:30.174438

"""

# revision identifiers, used by Alembic.
revision = '4ba6d29ce27f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'orders',
        sa.Column('order_no', sa.String(length=64), nullable=True),
        sa.Column('client_agency_name', sa.String(length=64), nullable=True),
        sa.Column('ship_to_name', sa.String(length=64), nullable=True),
        sa.Column('ship_to_street_add', sa.String(length=64), nullable=True),
        sa.Column('ship_to_street_add_2', sa.String(length=64), nullable=True),
        sa.Column('ship_to_city', sa.String(length=64), nullable=True),
        sa.Column('ship_to_state', sa.String(length=64), nullable=True),
        sa.Column('ship_to_zipcode', sa.String(length=64), nullable=True),
        sa.Column('ship_to_country', sa.String(length=64), nullable=True),
        sa.Column('ship_to_phone', sa.String(length=64), nullable=True),
        sa.Column('customer_email', sa.String(length=64), nullable=True),
        sa.Column('shipping_instructions', sa.String(length=64), nullable=True),
        sa.Column('clients_data', sa.Text(), nullable=True),
        sa.Column('confirmation_message', sa.Text(), nullable=True),
        sa.Column('date_received', sa.DateTime(), nullable=True),
        sa.Column('billing_name', sa.String(length=64), nullable=True),
        sa.Column('date_last_modified', sa.DateTime(), nullable=True),
        sa.Column('sub_order_no', sa.BigInteger(), nullable=False),
        sa.Column('client_id', sa.Integer(), nullable=True),
        sa.Column('order_types', sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint('sub_order_no')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    ### end Alembic commands ###
