"""Update birth_cert, birth_search, death_cert, death_search table

Revision ID: 66b7626d3457
Revises: a19565fcefcd
Create Date: 2022-04-18 14:45:51.551076

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '66b7626d3457'
down_revision = 'a19565fcefcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hvr',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('link', sa.String(length=256), nullable=False),
                    sa.Column('record_id', sa.String(length=64), nullable=False),
                    sa.Column('type', sa.String(length=16), nullable=False),
                    sa.Column('num_copies', sa.String(length=40), nullable=False),
                    sa.Column('exemplification', sa.Boolean(), nullable=False),
                    sa.Column('exemplification_copies', sa.String(length=1), nullable=True),
                    sa.Column('raised_seal', sa.Boolean(), nullable=False),
                    sa.Column('raised_seal_copies', sa.String(length=1), nullable=True),
                    sa.Column('no_amends', sa.Boolean(), nullable=False),
                    sa.Column('no_amends_copies', sa.String(length=1), nullable=True),
                    sa.Column('delivery_method', postgresql.ENUM('mail', 'email', 'pickup', name='delivery_method', create_type=False),
                              nullable=False),
                    sa.Column('suborder_number', sa.String(length=32), nullable=False),
                    sa.ForeignKeyConstraint(['suborder_number'], ['suborders.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.add_column('birth_cert', sa.Column('alt_first_name', sa.String(length=40), nullable=True))
    op.add_column('birth_cert', sa.Column('alt_last_name', sa.String(length=25), nullable=True))
    op.add_column('birth_cert', sa.Column('alt_middle_name', sa.String(length=40), nullable=True))
    op.add_column('birth_cert', sa.Column('exemplification_copies', sa.String(length=1), nullable=True))
    op.add_column('birth_cert', sa.Column('raised_seal', sa.Boolean(), nullable=False))
    op.add_column('birth_cert', sa.Column('raised_seal_copies', sa.String(length=1), nullable=True))
    op.add_column('birth_cert', sa.Column('no_amends', sa.Boolean(), nullable=False))
    op.add_column('birth_cert', sa.Column('no_amends_copies', sa.String(length=1), nullable=True))
    op.alter_column('birth_cert', 'letter', nullable=True, new_column_name='exemplification')

    op.add_column('birth_search', sa.Column('alt_first_name', sa.String(length=40), nullable=True))
    op.add_column('birth_search', sa.Column('alt_last_name', sa.String(length=25), nullable=True))
    op.add_column('birth_search', sa.Column('alt_middle_name', sa.String(length=40), nullable=True))
    op.add_column('birth_search', sa.Column('exemplification_copies', sa.String(length=1), nullable=True))
    op.add_column('birth_search', sa.Column('raised_seal', sa.Boolean(), nullable=False))
    op.add_column('birth_search', sa.Column('raised_seal_copies', sa.String(length=1), nullable=True))
    op.add_column('birth_search', sa.Column('no_amends', sa.Boolean(), nullable=False))
    op.add_column('birth_search', sa.Column('no_amends_copies', sa.String(length=1), nullable=True))
    op.alter_column('birth_search', 'letter', nullable=True, new_column_name='exemplification')

    op.add_column('death_cert', sa.Column('alt_last_name', sa.String(length=25), nullable=True))
    op.add_column('death_cert', sa.Column('alt_first_name', sa.String(length=40), nullable=True))
    op.add_column('death_cert', sa.Column('alt_middle_name', sa.String(length=40), nullable=True))
    op.add_column('death_cert', sa.Column('age_at_death', sa.String(length=3), nullable=True))
    op.add_column('death_cert', sa.Column('exemplification_copies', sa.String(length=1), nullable=True))
    op.add_column('death_cert', sa.Column('raised_seal', sa.Boolean(), nullable=False))
    op.add_column('death_cert', sa.Column('raised_seal_copies', sa.String(length=1), nullable=True))
    op.add_column('death_cert', sa.Column('no_amends', sa.Boolean(), nullable=False))
    op.add_column('death_cert', sa.Column('no_amends_copies', sa.String(length=1), nullable=True))
    op.alter_column('death_cert', 'letter', nullable=True, new_column_name='exemplification')

    op.add_column('death_search', sa.Column('alt_last_name', sa.String(length=25), nullable=True))
    op.add_column('death_search', sa.Column('alt_first_name', sa.String(length=40), nullable=True))
    op.add_column('death_search', sa.Column('alt_middle_name', sa.String(length=40), nullable=True))
    op.add_column('death_search', sa.Column('age_at_death', sa.String(length=3), nullable=True))
    op.add_column('death_search', sa.Column('exemplification_copies', sa.String(length=1), nullable=True))
    op.add_column('death_search', sa.Column('raised_seal', sa.Boolean(), nullable=False))
    op.add_column('death_search', sa.Column('raised_seal_copies', sa.String(length=1), nullable=True))
    op.add_column('death_search', sa.Column('no_amends', sa.Boolean(), nullable=False))
    op.add_column('death_search', sa.Column('no_amends_copies', sa.String(length=1), nullable=True))
    op.alter_column('death_search', 'letter', nullable=True, new_column_name='exemplification')


def downgrade():
    op.alter_column('death_search', 'exemplification', nullable=True, new_column_name='letter')
    op.drop_column('death_search', 'no_amends_copies')
    op.drop_column('death_search', 'no_amends')
    op.drop_column('death_search', 'raised_seal_copies')
    op.drop_column('death_search', 'raised_seal')
    op.drop_column('death_search', 'exemplification_copies')
    op.drop_column('death_search', 'age_at_death')
    op.drop_column('death_search', 'alt_middle_name')
    op.drop_column('death_search', 'alt_first_name')
    op.drop_column('death_search', 'alt_last_name')

    op.alter_column('death_cert', 'exemplification', nullable=True, new_column_name='letter')
    op.drop_column('death_cert', 'no_amends_copies')
    op.drop_column('death_cert', 'no_amends')
    op.drop_column('death_cert', 'raised_seal_copies')
    op.drop_column('death_cert', 'raised_seal')
    op.drop_column('death_cert', 'exemplification_copies')
    op.drop_column('death_cert', 'age_at_death')
    op.drop_column('death_cert', 'alt_middle_name')
    op.drop_column('death_cert', 'alt_first_name')
    op.drop_column('death_cert', 'alt_last_name')

    op.alter_column('birth_search', 'exemplification', nullable=True, new_column_name='letter')
    op.drop_column('birth_search', 'no_amends_copies')
    op.drop_column('birth_search', 'no_amends')
    op.drop_column('birth_search', 'raised_seal_copies')
    op.drop_column('birth_search', 'raised_seal')
    op.drop_column('birth_search', 'exemplification_copies')
    op.drop_column('birth_search', 'alt_middle_name')
    op.drop_column('birth_search', 'alt_last_name')
    op.drop_column('birth_search', 'alt_first_name')

    op.alter_column('birth_cert', 'exemplification', nullable=True, new_column_name='letter')
    op.drop_column('birth_cert', 'no_amends_copies')
    op.drop_column('birth_cert', 'no_amends')
    op.drop_column('birth_cert', 'raised_seal_copies')
    op.drop_column('birth_cert', 'raised_seal')
    op.drop_column('birth_cert', 'exemplification_copies')
    op.drop_column('birth_cert', 'alt_middle_name')
    op.drop_column('birth_cert', 'alt_last_name')
    op.drop_column('birth_cert', 'alt_first_name')
    op.drop_table('HVR')
