"""empty message

Revision ID: b35698ecc2cd
Revises: 57177d9e4818
Create Date: 2017-11-20 08:58:46.028484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b35698ecc2cd'
down_revision = '57177d9e4818'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('birth_cert', sa.Column('certificate_no', sa.String(length=40), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('birth_cert', 'certificate_no')
    # ### end Alembic commands ###
